version: '3'

services:
  minio:
    image: minio/minio
    ports:
      - "9009:9000"
      - "9001:9001"
    volumes:
      - ./minio_storage:/data
    environment:
      MINIO_ROOT_USER: horhevah
      MINIO_ROOT_PASSWORD: horhevah_pass
      INIO_SECRET_KEY: minio123
    command: server --console-address ":9001" /data

  createbuckets:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc alias set myminio http://minio:9000 horhevah horhevah_pass;
      /usr/bin/mc mb myminio/horhevah-bucket;
      /usr/bin/mc policy set public myminio/horhevah-bucket;
      exit 0;
      "

volumes:
  minio_storage: {}
