version: '3'
#networks:
#  web:
#    external: true
services:
  memes_api:
    restart: always
    build:
      context: ./memes_api
    # image: diagnost

    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_PASS: memes_pass
      DB_USER: postgres
      DB_NAME: postgres
      MINIO_API_HOST: minio_api
      MINIO_API_PORT: 8000

    depends_on:
      - db
      - minio_api

  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_PASSWORD: memes_pass
      POSTGRES_DB: postgres
      POSTGRES_INITDB_ARGS: --auth-host=scram-sha-256
    ports:
      - "5435:5432"

  minio_api:
    restart: always
    build:
      context: ./minio_api
    # image: diagnost

    environment:
      BUCKET_NAME: memes-bucket
      MINIO_HOST : minio
      MINIO_PORT : 9000

    depends_on:
      - minio
      - createbuckets

  minio:
    image: minio/minio
#    ports:
#      - "9009:9000"
#      - "9001:9001"
    #    volumes:
    #      - ./minio_storage:/data
    environment:
      MINIO_ROOT_USER: memes_user
      MINIO_ROOT_PASSWORD: memes_pass
      MINIO_SECRET_KEY: minio123
    command: server --console-address ":9001" /data

  createbuckets:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc alias set myminio http://minio:9000 memes_user memes_pass;
      /usr/bin/mc mb myminio/memes-bucket;      
      exit 0;
      "

  nginx:
    restart: always
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./nginx_config:/etc/nginx/conf.d/
    depends_on:
      - memes_api
