version: '3'
#networks:
#  web:
#    external: true
services:
 postgres-diagnost:
    image: postgres:14
    environment:
      POSTGRES_PASSWORD: mad127
      POSTGRES_DB: postgres
    ports:
    - "5488:5432"


