version: '3'

services:
  minio:
    image: minio/minio
    ports:
      - "9009:9000"
      - "9001:9001"
#    volumes:
#      - ./minio_storage:/data
    environment:
      MINIO_ROOT_USER: memes_user
      MINIO_ROOT_PASSWORD: memes_pass
      MINIO_SECRET_KEY: minio123
    command: server --console-address ":9001" /data

  createbuckets:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc alias set myminio http://minio:9000 memes_user memes_pass;
      /usr/bin/mc mb myminio/memes-bucket;      
      exit 0;
      "
#/usr/bin/mc anonymous set public myminio/memes-bucket;
#      /usr/bin/mc policy set public myminio/memes-bucket;
#      /usr/bin/mc admin policy attach myminio/memes-bucket readwrite --user horhevah;

#volumes:
#  minio_storage: {}
